version: "3.8"

services:
  bd_teste:
    image: mysql:5.7
    container_name: bd_teste
    restart: always
    volumes:
      - "./database/mysql_bd:/var/lib/mysql"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker 
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=teste 
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      
  # redis:
  #   image: "redis:alpine"
  #   container_name: redis-server
  #   restart: always
  #   command: redis-server --requirepass 'mobsystem_sispem12312' --appendonly yes
  #   volumes:
  #     - "./redis/data:/data"
  #   ports:
  #     - "6379:6379"

  # Application service layer
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_app
    working_dir: /usr/app
    # restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - "bd_teste"
      # - "redis"